//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CustomLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CustomLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICustomLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] CustomLangParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.viewStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitViewStatement([NotNull] CustomLangParser.ViewStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.pragma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPragma([NotNull] CustomLangParser.PragmaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.pragmaSetting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPragmaSetting([NotNull] CustomLangParser.PragmaSettingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.separatorValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeparatorValue([NotNull] CustomLangParser.SeparatorValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerType([NotNull] CustomLangParser.IntegerTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.globalVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVariableDeclaration([NotNull] CustomLangParser.GlobalVariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] CustomLangParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDefinition([NotNull] CustomLangParser.FunctionDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.functionVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionVariable([NotNull] CustomLangParser.FunctionVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CustomLangParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] CustomLangParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarator([NotNull] CustomLangParser.VariableDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.assignInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignInit([NotNull] CustomLangParser.AssignInitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] CustomLangParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.complexExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexExpression([NotNull] CustomLangParser.ComplexExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseStatement([NotNull] CustomLangParser.CaseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] CustomLangParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.iferrStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIferrStatement([NotNull] CustomLangParser.IferrStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStatement([NotNull] CustomLangParser.ForStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStatement([NotNull] CustomLangParser.WhileStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeatStatement([NotNull] CustomLangParser.RepeatStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] CustomLangParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.subCasFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubCasFunctionCall([NotNull] CustomLangParser.SubCasFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.subFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubFunctionCall([NotNull] CustomLangParser.SubFunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.killStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKillStatement([NotNull] CustomLangParser.KillStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] CustomLangParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] CustomLangParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.storeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStoreStatement([NotNull] CustomLangParser.StoreStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CustomLangParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] CustomLangParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.matrix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatrix([NotNull] CustomLangParser.MatrixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] CustomLangParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.complex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplex([NotNull] CustomLangParser.ComplexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.integralExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegralExpression([NotNull] CustomLangParser.IntegralExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SimpleSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleSummation([NotNull] CustomLangParser.SimpleSummationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MultiSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiSummation([NotNull] CustomLangParser.MultiSummationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] CustomLangParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.idList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdList([NotNull] CustomLangParser.IdListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.derivativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDerivativeExpression([NotNull] CustomLangParser.DerivativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.sqrtExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSqrtExpression([NotNull] CustomLangParser.SqrtExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.listSum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListSum([NotNull] CustomLangParser.ListSumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.listProduct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListProduct([NotNull] CustomLangParser.ListProductContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.firstDifferences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFirstDifferences([NotNull] CustomLangParser.FirstDifferencesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.factorialExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactorialExpression([NotNull] CustomLangParser.FactorialExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.basetoReal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBasetoReal([NotNull] CustomLangParser.BasetoRealContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalOperator([NotNull] CustomLangParser.RelationalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOperator([NotNull] CustomLangParser.LogicalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.matrixAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatrixAccess([NotNull] CustomLangParser.MatrixAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CustomLangParser.listAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListAccess([NotNull] CustomLangParser.ListAccessContext context);
}
