//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CustomLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CustomLangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICustomLangListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CustomLangParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CustomLangParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.viewStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterViewStatement([NotNull] CustomLangParser.ViewStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.viewStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitViewStatement([NotNull] CustomLangParser.ViewStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.pragma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPragma([NotNull] CustomLangParser.PragmaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.pragma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPragma([NotNull] CustomLangParser.PragmaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.pragmaSetting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPragmaSetting([NotNull] CustomLangParser.PragmaSettingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.pragmaSetting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPragmaSetting([NotNull] CustomLangParser.PragmaSettingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.separatorValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeparatorValue([NotNull] CustomLangParser.SeparatorValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.separatorValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeparatorValue([NotNull] CustomLangParser.SeparatorValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerType([NotNull] CustomLangParser.IntegerTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerType([NotNull] CustomLangParser.IntegerTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.globalVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalVariableDeclaration([NotNull] CustomLangParser.GlobalVariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.globalVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalVariableDeclaration([NotNull] CustomLangParser.GlobalVariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclaration([NotNull] CustomLangParser.FunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclaration([NotNull] CustomLangParser.FunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefinition([NotNull] CustomLangParser.FunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefinition([NotNull] CustomLangParser.FunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.functionVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionVariable([NotNull] CustomLangParser.FunctionVariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.functionVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionVariable([NotNull] CustomLangParser.FunctionVariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CustomLangParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CustomLangParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] CustomLangParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] CustomLangParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarator([NotNull] CustomLangParser.VariableDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarator([NotNull] CustomLangParser.VariableDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.assignInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignInit([NotNull] CustomLangParser.AssignInitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.assignInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignInit([NotNull] CustomLangParser.AssignInitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] CustomLangParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] CustomLangParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.complexExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexExpression([NotNull] CustomLangParser.ComplexExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.complexExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexExpression([NotNull] CustomLangParser.ComplexExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseStatement([NotNull] CustomLangParser.CaseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseStatement([NotNull] CustomLangParser.CaseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] CustomLangParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] CustomLangParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.iferrStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIferrStatement([NotNull] CustomLangParser.IferrStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.iferrStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIferrStatement([NotNull] CustomLangParser.IferrStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] CustomLangParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] CustomLangParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] CustomLangParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] CustomLangParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatStatement([NotNull] CustomLangParser.RepeatStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatStatement([NotNull] CustomLangParser.RepeatStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] CustomLangParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] CustomLangParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.subCasFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubCasFunctionCall([NotNull] CustomLangParser.SubCasFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.subCasFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubCasFunctionCall([NotNull] CustomLangParser.SubCasFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.subFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubFunctionCall([NotNull] CustomLangParser.SubFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.subFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubFunctionCall([NotNull] CustomLangParser.SubFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.killStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKillStatement([NotNull] CustomLangParser.KillStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.killStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKillStatement([NotNull] CustomLangParser.KillStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStatement([NotNull] CustomLangParser.BreakStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStatement([NotNull] CustomLangParser.BreakStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStatement([NotNull] CustomLangParser.ContinueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStatement([NotNull] CustomLangParser.ContinueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.storeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStoreStatement([NotNull] CustomLangParser.StoreStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.storeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStoreStatement([NotNull] CustomLangParser.StoreStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CustomLangParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CustomLangParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] CustomLangParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] CustomLangParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.matrix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMatrix([NotNull] CustomLangParser.MatrixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.matrix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMatrix([NotNull] CustomLangParser.MatrixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] CustomLangParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] CustomLangParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.complex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplex([NotNull] CustomLangParser.ComplexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.complex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplex([NotNull] CustomLangParser.ComplexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.integralExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegralExpression([NotNull] CustomLangParser.IntegralExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.integralExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegralExpression([NotNull] CustomLangParser.IntegralExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SimpleSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleSummation([NotNull] CustomLangParser.SimpleSummationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SimpleSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleSummation([NotNull] CustomLangParser.SimpleSummationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiSummation([NotNull] CustomLangParser.MultiSummationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiSummation([NotNull] CustomLangParser.MultiSummationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] CustomLangParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] CustomLangParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.idList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdList([NotNull] CustomLangParser.IdListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.idList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdList([NotNull] CustomLangParser.IdListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.derivativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDerivativeExpression([NotNull] CustomLangParser.DerivativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.derivativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDerivativeExpression([NotNull] CustomLangParser.DerivativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.sqrtExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSqrtExpression([NotNull] CustomLangParser.SqrtExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.sqrtExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSqrtExpression([NotNull] CustomLangParser.SqrtExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.listSum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListSum([NotNull] CustomLangParser.ListSumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.listSum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListSum([NotNull] CustomLangParser.ListSumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.listProduct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListProduct([NotNull] CustomLangParser.ListProductContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.listProduct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListProduct([NotNull] CustomLangParser.ListProductContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.firstDifferences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFirstDifferences([NotNull] CustomLangParser.FirstDifferencesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.firstDifferences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFirstDifferences([NotNull] CustomLangParser.FirstDifferencesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.factorialExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactorialExpression([NotNull] CustomLangParser.FactorialExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.factorialExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactorialExpression([NotNull] CustomLangParser.FactorialExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.basetoReal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBasetoReal([NotNull] CustomLangParser.BasetoRealContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.basetoReal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBasetoReal([NotNull] CustomLangParser.BasetoRealContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalOperator([NotNull] CustomLangParser.RelationalOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalOperator([NotNull] CustomLangParser.RelationalOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOperator([NotNull] CustomLangParser.LogicalOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOperator([NotNull] CustomLangParser.LogicalOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.matrixAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMatrixAccess([NotNull] CustomLangParser.MatrixAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.matrixAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMatrixAccess([NotNull] CustomLangParser.MatrixAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.listAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListAccess([NotNull] CustomLangParser.ListAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.listAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListAccess([NotNull] CustomLangParser.ListAccessContext context);
}
