//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CustomLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICustomLangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CustomLangBaseListener : ICustomLangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] CustomLangParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] CustomLangParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.viewStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterViewStatement([NotNull] CustomLangParser.ViewStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.viewStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitViewStatement([NotNull] CustomLangParser.ViewStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.pragma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragma([NotNull] CustomLangParser.PragmaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.pragma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragma([NotNull] CustomLangParser.PragmaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.pragmaSetting"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragmaSetting([NotNull] CustomLangParser.PragmaSettingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.pragmaSetting"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragmaSetting([NotNull] CustomLangParser.PragmaSettingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.separatorValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeparatorValue([NotNull] CustomLangParser.SeparatorValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.separatorValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeparatorValue([NotNull] CustomLangParser.SeparatorValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.integerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerType([NotNull] CustomLangParser.IntegerTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.integerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerType([NotNull] CustomLangParser.IntegerTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Asignar_Valor</c>
	/// labeled alternative in <see cref="CustomLangParser.globalVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsignar_Valor([NotNull] CustomLangParser.Asignar_ValorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Asignar_Valor</c>
	/// labeled alternative in <see cref="CustomLangParser.globalVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsignar_Valor([NotNull] CustomLangParser.Asignar_ValorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Declarar_Funcion</c>
	/// labeled alternative in <see cref="CustomLangParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarar_Funcion([NotNull] CustomLangParser.Declarar_FuncionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Declarar_Funcion</c>
	/// labeled alternative in <see cref="CustomLangParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarar_Funcion([NotNull] CustomLangParser.Declarar_FuncionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDefinition([NotNull] CustomLangParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDefinition([NotNull] CustomLangParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.functionVariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionVariable([NotNull] CustomLangParser.FunctionVariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.functionVariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionVariable([NotNull] CustomLangParser.FunctionVariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CustomLangParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CustomLangParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] CustomLangParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] CustomLangParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarator([NotNull] CustomLangParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarator([NotNull] CustomLangParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.assignLocal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignLocal([NotNull] CustomLangParser.AssignLocalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.assignLocal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignLocal([NotNull] CustomLangParser.AssignLocalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] CustomLangParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] CustomLangParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.complexExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexExpression([NotNull] CustomLangParser.ComplexExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.complexExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexExpression([NotNull] CustomLangParser.ComplexExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.caseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseStatement([NotNull] CustomLangParser.CaseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.caseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseStatement([NotNull] CustomLangParser.CaseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] CustomLangParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] CustomLangParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.iferrStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIferrStatement([NotNull] CustomLangParser.IferrStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.iferrStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIferrStatement([NotNull] CustomLangParser.IferrStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] CustomLangParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] CustomLangParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] CustomLangParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] CustomLangParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.repeatStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeatStatement([NotNull] CustomLangParser.RepeatStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.repeatStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeatStatement([NotNull] CustomLangParser.RepeatStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrintConParentesis</c>
	/// labeled alternative in <see cref="CustomLangParser.printStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintConParentesis([NotNull] CustomLangParser.PrintConParentesisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrintConParentesis</c>
	/// labeled alternative in <see cref="CustomLangParser.printStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintConParentesis([NotNull] CustomLangParser.PrintConParentesisContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PrintSinParentesis</c>
	/// labeled alternative in <see cref="CustomLangParser.printStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintSinParentesis([NotNull] CustomLangParser.PrintSinParentesisContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PrintSinParentesis</c>
	/// labeled alternative in <see cref="CustomLangParser.printStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintSinParentesis([NotNull] CustomLangParser.PrintSinParentesisContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] CustomLangParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] CustomLangParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.subFunctionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubFunctionCall([NotNull] CustomLangParser.SubFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.subFunctionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubFunctionCall([NotNull] CustomLangParser.SubFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.killStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKillStatement([NotNull] CustomLangParser.KillStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.killStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKillStatement([NotNull] CustomLangParser.KillStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] CustomLangParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] CustomLangParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] CustomLangParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] CustomLangParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.storeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStoreStatement([NotNull] CustomLangParser.StoreStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.storeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStoreStatement([NotNull] CustomLangParser.StoreStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Suma_de_lista</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuma_de_lista([NotNull] CustomLangParser.Suma_de_listaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Suma_de_lista</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuma_de_lista([NotNull] CustomLangParser.Suma_de_listaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParentesisExpression</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParentesisExpression([NotNull] CustomLangParser.ParentesisExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParentesisExpression</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParentesisExpression([NotNull] CustomLangParser.ParentesisExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ComplexStructures</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexStructures([NotNull] CustomLangParser.ComplexStructuresContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ComplexStructures</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexStructures([NotNull] CustomLangParser.ComplexStructuresContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Sumatoria</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSumatoria([NotNull] CustomLangParser.SumatoriaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Sumatoria</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSumatoria([NotNull] CustomLangParser.SumatoriaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryLogical</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryLogical([NotNull] CustomLangParser.UnaryLogicalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryLogical</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryLogical([NotNull] CustomLangParser.UnaryLogicalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BasicValues</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasicValues([NotNull] CustomLangParser.BasicValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BasicValues</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasicValues([NotNull] CustomLangParser.BasicValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleRelational</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleRelational([NotNull] CustomLangParser.SingleRelationalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleRelational</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleRelational([NotNull] CustomLangParser.SingleRelationalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Producto_de_lista</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProducto_de_lista([NotNull] CustomLangParser.Producto_de_listaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Producto_de_lista</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProducto_de_lista([NotNull] CustomLangParser.Producto_de_listaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Integracion</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegracion([NotNull] CustomLangParser.IntegracionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Integracion</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegracion([NotNull] CustomLangParser.IntegracionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Primeras_diferencias_de_lista</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimeras_diferencias_de_lista([NotNull] CustomLangParser.Primeras_diferencias_de_listaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Primeras_diferencias_de_lista</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimeras_diferencias_de_lista([NotNull] CustomLangParser.Primeras_diferencias_de_listaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Exponentiation</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExponentiation([NotNull] CustomLangParser.ExponentiationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Exponentiation</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExponentiation([NotNull] CustomLangParser.ExponentiationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Derivada</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDerivada([NotNull] CustomLangParser.DerivadaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Derivada</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDerivada([NotNull] CustomLangParser.DerivadaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>RaizCuadrada</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRaizCuadrada([NotNull] CustomLangParser.RaizCuadradaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>RaizCuadrada</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRaizCuadrada([NotNull] CustomLangParser.RaizCuadradaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalExpression</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalExpression([NotNull] CustomLangParser.LogicalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalExpression</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalExpression([NotNull] CustomLangParser.LogicalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AdditionOrSubtraction</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditionOrSubtraction([NotNull] CustomLangParser.AdditionOrSubtractionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AdditionOrSubtraction</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditionOrSubtraction([NotNull] CustomLangParser.AdditionOrSubtractionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryNegation</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryNegation([NotNull] CustomLangParser.UnaryNegationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryNegation</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryNegation([NotNull] CustomLangParser.UnaryNegationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiplicationOrDivision</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicationOrDivision([NotNull] CustomLangParser.MultiplicationOrDivisionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiplicationOrDivision</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicationOrDivision([NotNull] CustomLangParser.MultiplicationOrDivisionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionAccess</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionAccess([NotNull] CustomLangParser.FunctionAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionAccess</c>
	/// labeled alternative in <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionAccess([NotNull] CustomLangParser.FunctionAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] CustomLangParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] CustomLangParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.matrix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMatrix([NotNull] CustomLangParser.MatrixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.matrix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMatrix([NotNull] CustomLangParser.MatrixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] CustomLangParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] CustomLangParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.complex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplex([NotNull] CustomLangParser.ComplexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.complex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplex([NotNull] CustomLangParser.ComplexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.integralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegralExpression([NotNull] CustomLangParser.IntegralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.integralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegralExpression([NotNull] CustomLangParser.IntegralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SimpleSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleSummation([NotNull] CustomLangParser.SimpleSummationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SimpleSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleSummation([NotNull] CustomLangParser.SimpleSummationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiSummation([NotNull] CustomLangParser.MultiSummationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiSummation([NotNull] CustomLangParser.MultiSummationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] CustomLangParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] CustomLangParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.idList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdList([NotNull] CustomLangParser.IdListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.idList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdList([NotNull] CustomLangParser.IdListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.derivativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDerivativeExpression([NotNull] CustomLangParser.DerivativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.derivativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDerivativeExpression([NotNull] CustomLangParser.DerivativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.sqrtExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSqrtExpression([NotNull] CustomLangParser.SqrtExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.sqrtExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSqrtExpression([NotNull] CustomLangParser.SqrtExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.listSum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListSum([NotNull] CustomLangParser.ListSumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.listSum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListSum([NotNull] CustomLangParser.ListSumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.listProduct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListProduct([NotNull] CustomLangParser.ListProductContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.listProduct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListProduct([NotNull] CustomLangParser.ListProductContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.firstDifferences"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFirstDifferences([NotNull] CustomLangParser.FirstDifferencesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.firstDifferences"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFirstDifferences([NotNull] CustomLangParser.FirstDifferencesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.factorialExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactorialExpression([NotNull] CustomLangParser.FactorialExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.factorialExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactorialExpression([NotNull] CustomLangParser.FactorialExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.basetoReal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasetoReal([NotNull] CustomLangParser.BasetoRealContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.basetoReal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasetoReal([NotNull] CustomLangParser.BasetoRealContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.relationalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalOperator([NotNull] CustomLangParser.RelationalOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.relationalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalOperator([NotNull] CustomLangParser.RelationalOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.logicalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOperator([NotNull] CustomLangParser.LogicalOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.logicalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOperator([NotNull] CustomLangParser.LogicalOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.matrixAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMatrixAccess([NotNull] CustomLangParser.MatrixAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.matrixAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMatrixAccess([NotNull] CustomLangParser.MatrixAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.listAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListAccess([NotNull] CustomLangParser.ListAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.listAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListAccess([NotNull] CustomLangParser.ListAccessContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
