//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CustomLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICustomLangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CustomLangBaseListener : ICustomLangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] CustomLangParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] CustomLangParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.viewStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterViewStatement([NotNull] CustomLangParser.ViewStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.viewStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitViewStatement([NotNull] CustomLangParser.ViewStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.pragma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragma([NotNull] CustomLangParser.PragmaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.pragma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragma([NotNull] CustomLangParser.PragmaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.pragmaSetting"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragmaSetting([NotNull] CustomLangParser.PragmaSettingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.pragmaSetting"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragmaSetting([NotNull] CustomLangParser.PragmaSettingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.separatorValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeparatorValue([NotNull] CustomLangParser.SeparatorValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.separatorValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeparatorValue([NotNull] CustomLangParser.SeparatorValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.integerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerType([NotNull] CustomLangParser.IntegerTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.integerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerType([NotNull] CustomLangParser.IntegerTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.globalVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalVariableDeclaration([NotNull] CustomLangParser.GlobalVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.globalVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalVariableDeclaration([NotNull] CustomLangParser.GlobalVariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclaration([NotNull] CustomLangParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclaration([NotNull] CustomLangParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDefinition([NotNull] CustomLangParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.functionDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDefinition([NotNull] CustomLangParser.FunctionDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.functionVariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionVariable([NotNull] CustomLangParser.FunctionVariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.functionVariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionVariable([NotNull] CustomLangParser.FunctionVariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CustomLangParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CustomLangParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] CustomLangParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] CustomLangParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarator([NotNull] CustomLangParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarator([NotNull] CustomLangParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.assignInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignInit([NotNull] CustomLangParser.AssignInitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.assignInit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignInit([NotNull] CustomLangParser.AssignInitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] CustomLangParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] CustomLangParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.complexExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexExpression([NotNull] CustomLangParser.ComplexExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.complexExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexExpression([NotNull] CustomLangParser.ComplexExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.caseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseStatement([NotNull] CustomLangParser.CaseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.caseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseStatement([NotNull] CustomLangParser.CaseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] CustomLangParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] CustomLangParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.iferrStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIferrStatement([NotNull] CustomLangParser.IferrStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.iferrStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIferrStatement([NotNull] CustomLangParser.IferrStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] CustomLangParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] CustomLangParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] CustomLangParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] CustomLangParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.repeatStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeatStatement([NotNull] CustomLangParser.RepeatStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.repeatStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeatStatement([NotNull] CustomLangParser.RepeatStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] CustomLangParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] CustomLangParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.subCasFunctionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubCasFunctionCall([NotNull] CustomLangParser.SubCasFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.subCasFunctionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubCasFunctionCall([NotNull] CustomLangParser.SubCasFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.subFunctionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubFunctionCall([NotNull] CustomLangParser.SubFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.subFunctionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubFunctionCall([NotNull] CustomLangParser.SubFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.killStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKillStatement([NotNull] CustomLangParser.KillStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.killStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKillStatement([NotNull] CustomLangParser.KillStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] CustomLangParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] CustomLangParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] CustomLangParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] CustomLangParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] CustomLangParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.storeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStoreStatement([NotNull] CustomLangParser.StoreStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.storeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStoreStatement([NotNull] CustomLangParser.StoreStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CustomLangParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CustomLangParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] CustomLangParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] CustomLangParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.matrix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMatrix([NotNull] CustomLangParser.MatrixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.matrix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMatrix([NotNull] CustomLangParser.MatrixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] CustomLangParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] CustomLangParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.complex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplex([NotNull] CustomLangParser.ComplexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.complex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplex([NotNull] CustomLangParser.ComplexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.integralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegralExpression([NotNull] CustomLangParser.IntegralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.integralExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegralExpression([NotNull] CustomLangParser.IntegralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SimpleSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleSummation([NotNull] CustomLangParser.SimpleSummationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SimpleSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleSummation([NotNull] CustomLangParser.SimpleSummationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiSummation([NotNull] CustomLangParser.MultiSummationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiSummation</c>
	/// labeled alternative in <see cref="CustomLangParser.summationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiSummation([NotNull] CustomLangParser.MultiSummationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] CustomLangParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] CustomLangParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.idList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdList([NotNull] CustomLangParser.IdListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.idList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdList([NotNull] CustomLangParser.IdListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.derivativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDerivativeExpression([NotNull] CustomLangParser.DerivativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.derivativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDerivativeExpression([NotNull] CustomLangParser.DerivativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.sqrtExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSqrtExpression([NotNull] CustomLangParser.SqrtExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.sqrtExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSqrtExpression([NotNull] CustomLangParser.SqrtExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.listSum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListSum([NotNull] CustomLangParser.ListSumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.listSum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListSum([NotNull] CustomLangParser.ListSumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.listProduct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListProduct([NotNull] CustomLangParser.ListProductContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.listProduct"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListProduct([NotNull] CustomLangParser.ListProductContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.firstDifferences"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFirstDifferences([NotNull] CustomLangParser.FirstDifferencesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.firstDifferences"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFirstDifferences([NotNull] CustomLangParser.FirstDifferencesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.factorialExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactorialExpression([NotNull] CustomLangParser.FactorialExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.factorialExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactorialExpression([NotNull] CustomLangParser.FactorialExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.basetoReal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBasetoReal([NotNull] CustomLangParser.BasetoRealContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.basetoReal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBasetoReal([NotNull] CustomLangParser.BasetoRealContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.relationalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalOperator([NotNull] CustomLangParser.RelationalOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.relationalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalOperator([NotNull] CustomLangParser.RelationalOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.logicalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOperator([NotNull] CustomLangParser.LogicalOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.logicalOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOperator([NotNull] CustomLangParser.LogicalOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.matrixAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMatrixAccess([NotNull] CustomLangParser.MatrixAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.matrixAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMatrixAccess([NotNull] CustomLangParser.MatrixAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CustomLangParser.listAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListAccess([NotNull] CustomLangParser.ListAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CustomLangParser.listAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListAccess([NotNull] CustomLangParser.ListAccessContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
